
FROM node:12.18.1
#FROM node:12.18.1-alpine

WORKDIR /usr/src/app
COPY package*.json ./
#COPY *.json ./
COPY *.js ./
COPY *.sh ./
RUN npm install 
CMD npm config set cache-min 9999999 && \
    npm install && \
    npm run start:dev
