
version: '3'
services: 

  
  spaces-storage:
    image: spaces-storage
    build: 
      context: ./spaces-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=<insert your Azure storage account name here>
      - STORAGE_ACCESS_KEY=<insert your Azure storage account access key here>
    restart: "no"
