
version: '3'
services: 

  
  data-mongodb:
    image: data-mongodb
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile-dev
    container_name: data-mongodb
    ports:
     - 27017:27017
    volumes:
        - ./data-mongodb:/usr/src/app:z
    expose:
     - 27017
    restart: always
