
version: '3'
services: 

  
  data-mongodb:
    image: data-mongodb
    #image: mongo:4.2.8
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile
    container_name: data-mongodb
    expose:
     - 27017
     - 30000
    restart: always
  
  push-mongodb:
    image: push-mongodb
    build: 
      context: ./push-mongodb
      dockerfile: Dockerfile
    container_name: push-mongodb
    ports:
     - "5000:80"
    environment:
      - DB=earthquakes
      - COLLECTION=largest_earthquakes_export
    restart: always
