
version: '3'
services: 

  
  data-mongodb:
    image: data-mongodb
    #image: mongo:4.2.8
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile
    container_name: data-mongodb
    ports:
     - "4000:27017"
    restart: always
