
version: '3'
services: 

  
  spaces-storage:
    image: spaces-storage
    build: 
      context: ./spaces-storage
      dockerfile: Dockerfile
    container_name: spaces-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    restart: "no"
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=spaces-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    depends_on:
      - data-mongodb
    restart: "no"
  
  data-mongodb:
    image: data-mongodb
    #image: mongo:4.2.8
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile
    container_name: data-mongodb
    expose:
     - 27017
     - 30000
    restart: always
