
version: '3'
services: 

  
  data-mongodb:
    image: data-mongodb
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile-dev
    container_name: data-mongodb
    ports:
     - 27017:27017
    expose:
     - 27017
    restart: always
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=spaces-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://data-mongodb:27017
      - DBNAME=video-streaming
    #depends_on:
    #  - data-mongodb
    restart: "no"
  
  push-mongodb:
    image: push-mongodb
    build: 
      context: ./push-mongodb
      dockerfile: Dockerfile
    container_name: push-mongodb
    ports:
     - "5000:80"
    environment:
      - DB=earthquakes
      - COLLECTION=largest_earthquakes_export
    restart: always
  
  spaces-storage:
    image: spaces-storage
    build: 
      context: ./spaces-storage
      dockerfile: Dockerfile
    container_name: spaces-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    restart: "no"
