version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4000:27017"
    restart: always

  do-storage:
    image: do-storage
    build: 
      context: ./do-storage
      dockerfile: Dockerfile
    container_name: do-storage
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=<insert your Azure storage account name here>
      - STORAGE_ACCESS_KEY=<insert your Azure storage account access key here>
    restart: "no"

  node-helloworld:
    image: node-helloworld
    build: 
      context: ./node-helloworld
      dockerfile: Dockerfile
    container_name: node-helloworld
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"
