
version: '3'
services: 

  
  data-mongodb:
    image: data-mongodb
    build: 
      context: ./data-mongodb
      dockerfile: Dockerfile-dev
    container_name: data-mongodb
    ports:
     - 27017:27017
    volumes:
        - ./data-mongodb:/usr/src/app:z
    expose:
     - 27017
    restart: always
    

  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
    

  history:
    image: history
    build: 
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://data-mongodb:27017
      - DBNAME=history
      - NODE_ENV=development
    #depends_on:
    #  - db
    #  - rabbit
    restart: "no"
  
    

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
     - PORT=80
     - VIDEO_STORAGE_HOST=spaces-storage
     - VIDEO_STORAGE_PORT=80
     - DBHOST=mongodb://data-mongodb:27017
     - DBNAME=video-streaming
     - RABBIT=amqp://guest:guest@rabbit:5672
    volumes:
     - ./video-streaming:/usr/src/app:z
    #depends_on:
    #- data-mongodb
    restart: "no"
  
  spaces-storage:
    image: spaces-storage
    build: 
      context: ./spaces-storage
      dockerfile: Dockerfile-dev
    container_name: spaces-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./spaces-storage:/usr/src/app:z
        - /tmp/history/npm-cache:/root/.npm:z
    restart: "no"
  
  push-mongodb:
    image: push-mongodb
    build: 
      context: ./push-mongodb
      dockerfile: Dockerfile-dev
    container_name: push-mongodb
    ports:
     - "5000:80"
    environment:
      - PORT=80
      - DB=earthquakes
      - COLLECTION=largest_earthquakes_export
      - NODE_ENV=development
    volumes:
        - ./push-mongodb:/usr/src/app:z
        - /tmp/history/npm-cache:/root/.npm:z
    restart: 'no'
