
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-helloworld
  template:
    metadata:
      labels:
        app: node-helloworld
    spec:
      containers:
      - name: node-container
        image: node-helloworld:v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
