apiVersion: v1
kind: Service
metadata:
  name: node-helloworld-service
spec:
  selector:
    app: node-helloworld 
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
