apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: star-wars
