#FROM node:12.18.1-alpine
FROM node:12.18.1

WORKDIR /usr/src/app
#COPY package*.json ./
#RUN npm install --only=production
#COPY ./src ./src
CMD npm config set cache-min 9999999 && \
    npm install && \
    npm run start:dev

